# Welcome to Jekyll!
title: Online &hearts; Resume
url:
baseurl:

# Sass setting
sass:
  sass_dir: _sass
  style:    compressed

# Custom
lang: en                    # html lang
open: true                  # open or close your site
date_format: "%Y-%m-%d"     # date format
google_analytics:           # your google analytics
theme_color: "#0080FF"      # your favorite theme color
